kaizen/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kaizen.views.home', name='home'),
    # url(r'^kaizen/', include('kaizen.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^users', RedirectView.as_view(url='/')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^', include('suggestionbox.urls', namespace='suggestionbox')),
    url(r'^twitter', include('twitter.urls', namespace='twitter')),

)#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

suggestionbox/urls.py
from django.conf.urls import patterns, include, url
from suggestionbox import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^detail/(?P<suggestion_id>\d+)/$', views.detail, name='detail'),
    url(r'^category/(?P<category_id>\d+)/$', views.category, name='category'),
    url(r'^status/(?P<status_id>\d+)/$', views.status, name='status'),
    url(r'^detail/(?P<suggestion_id>\d+)/add_comment/$', views.add_comment, name='add_comment'),
    url(r'^detail/(?P<suggestion_id>\d+)/edit_status/$', views.edit_status, name='edit_status'),
    url(r'^add_suggestion/$', views.add_suggestion, name='add_suggestion'),
)

suggestionbox/models.py
from django.db import models
from django.contrib.auth.models import User
class Suggestion(models.Model):
	user = models.ForeignKey(User)
	title = models.CharField(max_length=100)
	description = models.TextField()
	pub_date = models.DateTimeField(auto_now_add=True) #automattically puts the time stamp in
	status = models.ForeignKey('Status')
	category = models.ForeignKey('Category')
	
	def __unicode__(self):
		return self.title

class Status(models.Model):
	title = models.CharField(max_length=100)
	description = models.TextField()

	def __unicode__(self):
		return self.title

	class Meta:
		verbose_name_plural = 'statuses'


class Category(models.Model):
	title = models.CharField(max_length=100)
	description = models.TextField()
	
	def __unicode__(self):
		return self.title

	class Meta:
		verbose_name_plural = 'categories'

class Comment(models.Model):
	comment = models.TextField()
	user = models.ForeignKey(User)
	pub_date = models.DateTimeField(auto_now_add=True)
	sid = models.ForeignKey(Suggestion)

	def __unicode__(self):
		return self.comment[:50]

suggestionbox/forms.py
from django import forms
from django.forms import ModelForm
from suggestionbox.models import Comment, Suggestion, Status

class AddComment(ModelForm):
	class Meta:
		model = Comment
		widgets = {
          		'comment': forms.Textarea(attrs={'rows':3, 'cols':15}),
        	}
		fields=['comment']

class AddSuggestion(ModelForm):
	class Meta:
		model = Suggestion
		widgets = {
          		'description': forms.Textarea(attrs={'rows':3, 'cols':15}),
        	}
		fields=['title','description','category']

class EditStatus(ModelForm):
	class Meta:
		model= Suggestion
		fields=['status']

suggestionbox/views.py
# Create your views here.
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.core.mail import send_mail

from suggestionbox.models import Suggestion, Comment, Status, Category
from suggestionbox.forms import AddComment, AddSuggestion, EditStatus
# view for our index
@login_required
def index(request):
    suggestions = Suggestion.objects.all().order_by('-pub_date')
    categories = Category.objects.all()
    statuses = Status.objects.all()
    paginator = Paginator(suggestions, 5)
    page = request.GET.get('page')
    
    try:
        suggestions= paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        suggestions = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        suggestions = paginator.page(paginator.num_pages)
    user = request.user
    context = {
        'suggestions': suggestions,
	'user': user,
	'categories': categories,
	'statuses': statuses,
    }

    return render(request, 'suggestionbox/index.html', context)

@login_required
def detail(request, suggestion_id):
    suggestion = get_object_or_404(Suggestion, pk=suggestion_id)
    suggestions = Suggestion.objects.all().order_by('-pub_date')#for the navbar
    categories = Category.objects.all()
    statuses = Status.objects.all()
    comments = Comment.objects.all().filter(sid=suggestion_id)
    user = request.user
    context = {
        'suggestion': suggestion,
	'suggestions': suggestions,
	'comments': comments,
	'user': user,
        'categories': categories,
	'statuses': statuses,
    }

    return render(request, 'suggestionbox/detail.html', context)
@login_required
def add_comment(request, suggestion_id):
	suggestion = get_object_or_404(Suggestion, pk=suggestion_id)
	suggestions = Suggestion.objects.all().order_by('-pub_date')#for the navbar
        categories = Category.objects.all()
        statuses = Status.objects.all()
	comment = Comment(user=request.user, sid=suggestion)
	form = AddComment(request.POST or None, instance=comment)

	if form.is_valid():
		form.save()
		messages.success(request, 'Successfully added a comment.')
	elif form.errors:
		messages.error(request, 'Something went wrong, please try again.')
	context = {
        'suggestion': suggestion,
	'suggestions': suggestions,
	'form': form,
	'categories': categories,
	'statuses': statuses,
	}
	
	return render(request, 'suggestionbox/add_comment.html', context)
@login_required
def add_suggestion(request):
	default_status=Status(pk=1)#the default pending status
	suggestion = Suggestion(user=request.user, status=default_status)
	suggestions = Suggestion.objects.all().order_by('-pub_date')#for the navbar
        categories = Category.objects.all()
	statuses = Status.objects.all()

	form = AddSuggestion(request.POST or None, instance=suggestion)

	if form.is_valid():
		form.save()
		messages.success(request, 'Successfully added a suggestion.')
	elif form.errors:
		messages.error(request, 'Something went wrong, please try again.')
	context = {
	'suggestions': suggestions,
	'form': form,
	'categories': categories,
	'statuses': statuses,
	}
	
	return render(request, 'suggestionbox/add_suggestion.html', context)
@login_required
def edit_status(request, suggestion_id):
	suggestion = get_object_or_404(Suggestion, pk=suggestion_id)
	suggestions = Suggestion.objects.all().order_by('-pub_date')#for the navbar
        categories = Category.objects.all()
	statuses = Status.objects.all()
	form = EditStatus(request.POST or None, instance=suggestion)
	if request.user.id ==1: #we only submit the form if the user is the admin.
		if form.is_valid():
			form.save()
			messages.success(request, 'Status successfully modified.')
			#next line will send an email, that will shou up in the console, not actually to an email address...
			#suggestion.user.email_user('A suggestion you have mades status has been modified', 's status has been modified to ', 'sgoeddel247@gmail.com') 
	elif form.errors:
		messages.error(request, 'Something went wrong, please try again.')
	context = {
	'suggestions': suggestions,
	'suggestion': suggestion,
	'form': form,
	'categories': categories,
	'statuses': statuses,
	
	}
	
	return render(request, 'suggestionbox/edit_status.html', context)
@login_required
def category(request, category_id):
    suggestions = Suggestion.objects.all().filter(category = category_id).order_by('-pub_date')
    categories = Category.objects.all()
    statuses = Status.objects.all()
    cat = get_object_or_404(Category, pk=category_id)
    paginator = Paginator(suggestions, 5)
    page = request.GET.get('page')
    
    try:
        suggestions= paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        suggestions = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        suggestions = paginator.page(paginator.num_pages)

    user = request.user
    context = {
        'suggestions': suggestions,
	'user': user,
	'cat': cat,
	'categories': categories,
	'statuses': statuses,
    }

    return render(request, 'suggestionbox/category.html', context)

def status(request, status_id):
    suggestions = Suggestion.objects.all().filter(status = status_id).order_by('-pub_date')
    categories = Category.objects.all()
    statuses = Status.objects.all()
    status = get_object_or_404(Status, pk=status_id)
    paginator = Paginator(suggestions, 5)
    page = request.GET.get('page')
    
    try:
        suggestions= paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        suggestions = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        suggestions = paginator.page(paginator.num_pages)
    user = request.user
    context = {
        'suggestions': suggestions,
	'user': user,
	'status': status,
	'categories': categories,
	'statuses': statuses,
    }

    return render(request, 'suggestionbox/status.html', context)

suggestionbox/templates/suggestionbox/add_comment.html
{% extends 'base.html' %}

{% block title %}æ”¹å–„ - Add comment to {{ suggestion.title }}{% endblock %}

{% block content %}
	<a href='{% url 'suggestionbox:detail' suggestion.id %}'>Return to Previous Page</a>
	<h1>Adding a comment to:</h1>
	<h2>{{ suggestion.title }}</h2>
	<form method="POST" action="." id="comment-add-form">
		<table class="form">
		{% csrf_token %}
		{{form}}
		</table>
		<input class="btn" type="submit" value="Add Comment"></input>
	</form>
	{% if messages %}
		<ul class="messages">
			{% for message in messages %}
				<li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			{% endfor %}
		</ul>
	{% endif %}
{% endblock %}

suggestionbox/templates/suggestionbox/add_suggestion.html
{% extends 'base.html' %}

{% block title %}æ”¹å–„ - Add Suggestion{% endblock %}

{% block content %}
	<a href='{% url 'suggestionbox:index' %}'>Return to Previous Page</a>
	<h1>Adding a suggestion:</h1>
	<form method="POST" action="." id="suggestion-add-form">
		<table class="form">
		{% csrf_token %}
		{{form}}
		</table>
		<input class="btn" type="submit" value="Add Suggestion"></input>
	</form>
	{% if messages %}
		<ul class="messages">
			{% for message in messages %}
				<li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			{% endfor %}
		</ul>
	{% endif %}
{% endblock %}

suggestionbox/templates/suggestionbox/category.html
{% extends 'base.html' %}

{% block title %}æ”¹å–„ - List of suggestions{% endblock %}

{% block content %}


	{% if suggestions %}
	<h1>{{cat}}</h1>



	<table class="table">
	<tr>
	    <th>Author</th>
	    <th>Title</th>
	    <th>Description</th>
	    <th>Pub Date</th>
	    <th>Status</th>
	</tr>
	{% for suggestion in suggestions %}
		{% if user == suggestion.user %}
			<tr class="user">
		{% else %}
			<tr>
		{% endif %}
		    <td>{{ suggestion.user }}</td>
		    <td><a href="{% url 'suggestionbox:detail' suggestion.id %}">{{ suggestion.title }}</a></td>
		    <td>{{ suggestion.description }}</td>
		    <td>{{ suggestion.pub_date }}</td>
		    <td><a href="{% url 'suggestionbox:status' suggestion.status.id %}">{{ suggestion.status }}</a></td>
		</tr>

	{% endfor %}
	</table>
	
	{% else %}
	<h1>No suggestions Yet</h1>
	<p>Be the first of your friends to suggest something.</p>
	{% endif %}
	<div class="pagination">
		<span class="step-links">
			{% if suggestions.has_previous %}
			    <a href="?page={{ suggestions.previous_page_number }}"><</a>
			{% endif %}

			<span class="current">
			    Page {{ suggestions.number }} of {{ suggestions.paginator.num_pages }}
			</span>

			{% if suggestions.has_next %}
			    <a href="?page={{ suggestions.next_page_number }}">></a>
			{% endif %}
    		</span>


	</div>
	<div class="cur_user">
		<p>Welcome, {{user}}.</p>
	</div>
{% endblock %}

suggestionbox/templates/suggestionbox/detail.html
{% extends 'base.html' %}

{% block title %}æ”¹å–„ - Details for {{ suggestion.title }}{% endblock %}

{% block content %}

	<h1>{{ suggestion.title }}</h1>
	<div class = "info">
		<p> By: {{ suggestion.user }} on: {{ suggestion.pub_date }}</p>
		
		<p> Status: <a href="{% url 'suggestionbox:status' suggestion.status.id %}">{{ suggestion.status }}</a> Category: <a href="{% url 'suggestionbox:category' suggestion.category.id %}">{{ suggestion.category }}</a></p>
		<p class="desc">{{ suggestion.description }}</p>
		{% if user.id == 1 %}<!--the superuser is admin which is user.id of 1 -->
			<p><a href="{% url 'suggestionbox:edit_status' suggestion.id %}">Edit Status</a></p>
	
		{% endif %}
	</div>
	
	<div class="comments">
		<h2>Comments</h2>
		<a href="{% url 'suggestionbox:add_comment' suggestion.id %}">Add a comment</a>
		{% for comment in comments %}
			{% if comment.user == suggestion.user %}
				<div class="user">
			{% else %}
				<div class="info">
			{% endif %}
				<p> By: {{ comment.user }} on: {{ comment.pub_date }}</p>
				<p class="desc">{{comment.comment}}</p>
			</div>
		{% endfor %}
		
	</div>
	<div class="cur_user">
		<p>Welcome, {{user}}.</p>
	</div>

{% endblock %}

suggestionbox/templates/suggestionbox/edit_status.html
{% extends 'base.html' %}

{% block title %}æ”¹å–„ - Edit status of {{ suggestion.title }}{% endblock %}

{% block content %}
	<a href='{% url 'suggestionbox:detail' suggestion.id %}'>Return to Previous Page</a>
	<h1>Editing Status of:</h1>
	<h2>{{ suggestion.title }}</h2>
	<form method="POST" action="." id="status-edit-form">
		<table class="form">
		{% csrf_token %}
		{{form}}
		</table>
		<input class="btn" type="submit" value="Edit Status"></input>
	</form>
	{% if messages %}
		<ul class="messages">
			{% for message in messages %}
				<li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			{% endfor %}
		</ul>
	{% endif %}
{% endblock %}

suggestionbox/templates/suggestionbox/index.html
{% extends 'base.html' %}

{% block title %}æ”¹å–„ - List of Suggestions{% endblock %}

{% block content %}


	{% if suggestions %}
	<h1>Suggestions</h1>



	<table class="table">
	<tr>
	    <th>Author</th>
	    <th>Title</th>
	    <th>Description</th>
	    <th>Pub Date</th>
	    <th>Status</th>
	    <th>Category</th>
	</tr>
	{% for suggestion in suggestions %}
		{% if user == suggestion.user %}
			<tr class="user">
		{% else %}
			<tr>
		{% endif %}
		    <td>{{ suggestion.user }}</td>
		    <td><a href="{% url 'suggestionbox:detail' suggestion.id %}">{{ suggestion.title }}</a></td>
		    <td>{{ suggestion.description }}</td>
		    <td>{{ suggestion.pub_date }}</td>
		    <td><a href="{% url 'suggestionbox:status' suggestion.status.id %}">{{ suggestion.status }}</a></td>
		    <td><a href="{% url 'suggestionbox:category' suggestion.category.id %}">{{ suggestion.category }}</a></td>
		</tr>

	{% endfor %}
	</table>
	<a href="{% url 'suggestionbox:add_suggestion' %}">Add a suggestion</a>
	{% else %}
	<h1>No Suggestions Yet</h1>
	<p>Be the first of your friends to suggest something.</p>
	{% endif %}
	<div class="pagination">
		<span class="step-links">
			{% if suggestions.has_previous %}
			    <a href="?page={{ suggestions.previous_page_number }}"><</a>
			{% endif %}

			<span class="current">
			    Page {{ suggestions.number }} of {{ suggestions.paginator.num_pages }}
			</span>

			{% if suggestions.has_next %}
			    <a href="?page={{ suggestions.next_page_number }}">></a>
			{% endif %}
    		</span>


	</div>
	<div class="cur_user">
		<p>Welcome, {{user}}.</p>
	</div>
{% endblock %}

suggestionbox/templates/suggestionbox/status.html
{% extends 'base.html' %}

{% block title %}æ”¹å–„ - List of suggestions{% endblock %}

{% block content %}


	{% if suggestions %}
	<h1>{{status}}</h1>



	<table class="table">
	<tr>
	    <th>Author</th>
	    <th>Title</th>
	    <th>Description</th>
	    <th>Pub Date</th>
	    <th>Category</th>
	</tr>
	{% for suggestion in suggestions %}
		{% if user == suggestion.user %}
			<tr class="user">
		{% else %}
			<tr>
		{% endif %}
		    <td>{{ suggestion.user }}</td>
		    <td><a href="{% url 'suggestionbox:detail' suggestion.id %}">{{ suggestion.title }}</a></td>
		    <td>{{ suggestion.description }}</td>
		    <td>{{ suggestion.pub_date }}</td>
		    <td><a href="{% url 'suggestionbox:category' suggestion.category.id %}">{{ suggestion.category }}</a></td>
		</tr>

	{% endfor %}
	</table>
	
	{% else %}
	<h1>No suggestions Yet</h1>
	<p>Be the first of your friends to suggest something.</p>
	{% endif %}
	<div class="pagination">
		<span class="step-links">
			{% if suggestions.has_previous %}
			    <a href="?page={{ suggestions.previous_page_number }}"><</a>
			{% endif %}

			<span class="current">
			    Page {{ suggestions.number }} of {{ suggestions.paginator.num_pages }}
			</span>

			{% if suggestions.has_next %}
			    <a href="?page={{ suggestions.next_page_number }}">></a>
			{% endif %}
    		</span>


	</div>
	<div class="cur_user">
		<p>Welcome, {{user}}.</p>
	</div>
{% endblock %}