kaizen/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kaizen.views.home', name='home'),
    # url(r'^kaizen/', include('kaizen.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^users', RedirectView.as_view(url='/')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^', include('suggestionbox.urls', namespace='suggestionbox')),
    url(r'^twitter', include('twitter.urls', namespace='twitter')),

)#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

suggestionbox/urls.py
from django.conf.urls import patterns, include, url
from suggestionbox import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^detail/(?P<suggestion_id>\d+)/$', views.detail, name='detail'),
    url(r'^category/(?P<category_id>\d+)/$', views.category, name='category'),
    url(r'^status/(?P<status_id>\d+)/$', views.status, name='status'),
    url(r'^detail/(?P<suggestion_id>\d+)/add_comment/$', views.add_comment, name='add_comment'),
    url(r'^detail/(?P<suggestion_id>\d+)/edit_status/$', views.edit_status, name='edit_status'),
    url(r'^add_suggestion/$', views.add_suggestion, name='add_suggestion'),
)

twitter/urls.py
from django.conf.urls import patterns, include, url
from twitter import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^/profile/(?P<profile_id>\d+)/$', views.profile, name='profile'),
    url(r'^/profile/follow/(?P<profile_id>\d+)/(?P<fol>\d+)/$', views.follow, name='follow'),
    url(r'^/profile/edit/(?P<profile_id>\d+)/$', views.edit_profile, name='edit_profile'),
    url(r'^/profile/add/$', views.add_profile, name='add_profile'),
    url(r'^/add_post/$', views.add_post, name='add_post'),
    url(r'^/delete_post/(?P<post_id>\d+)/$', views.delete_post, name='delete_post'),
)

kaizen/templates/base.html
{% load staticfiles %}
<!DOCTYPE html> 
<html lang="en"> 
<head> 
	<meta charset="utf-8"> 
	{% block title %}<title>Kaizen-Suggestion Box</title>{% endblock %}
	<link rel ="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
	<link rel ="stylesheet" href="{% static 'style.css' %}">
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" ></script>
	<script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
	{% block scripts %}{% endblock %}
</head>
<body>
	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">
		<ul class="nav">
		  <li class="active">
		    <a class="brand" href="{% url 'suggestionbox:index' %}">Kaizen-Suggestion Box</a>
		  </li>
		  <li class="dropdown">
		    <a href="#"
			  class="dropdown-toggle"
			  data-toggle="dropdown">
			  Categories
			  <b class="caret"></b>
		    </a>
		    <ul class="dropdown-menu">
		     {% for category in categories %}
		     <li><a href="{% url 'suggestionbox:category' category.id %}">{{category.title}}</a></li>
		     {% endfor %}
		    </ul>
		  </li>
		  <li class="dropdown">
		    <a href="#"
			  class="dropdown-toggle"
			  data-toggle="dropdown">
			  Suggestions
			  <b class="caret"></b>
		    </a>
		    <ul class="dropdown-menu">
		     {% for suggestion in suggestions %}
		     <li><a href="{% url 'suggestionbox:detail' suggestion.id %}">{{suggestion.title}}</a></li>
		     {% endfor %}
		    </ul>
		  </li>
		  <li class="dropdown">
		    <a href="#"
			  class="dropdown-toggle"
			  data-toggle="dropdown">
			  Statuses
			  <b class="caret"></b>
		    </a>
		    <ul class="dropdown-menu">
		     {% for status in statuses %}
		     <li><a href="{% url 'suggestionbox:status' status.id %}">{{status.title}}</a></li>
		     {% endfor %}
		    </ul>
		  </li>
		</ul>
		 <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'auth_logout' %}"> Log Out</a></li>
                    {% else %}
                    <li><a href="{% url 'auth_login' %}"><span class="glyphicon glyphicon-user"></span> Log In</a></li>
                    {% endif %}
		    {% if user.is_superuser %}
			<li><a href="{% url 'admin:app_list' 'suggestionbox' %}">Admin</a></li>
		    {% endif %}
		    <li><a href="{% url 'twitter:index' %}">Twitter</a></li>
		    <li><a href="http://mysite.smg247.webfactional.com">Other Apps</a></li>
                </ul>

	    </div>
	  </div>
	</div> 
	<div class="content">
	{% block content %}

	{% endblock %}
		<div class="footer">
		Created by: Stephen Goeddel<br />
		On: 9/26/2013
	</div>
	</div>

</body>

</html>

kaizen/templates/basic_base.html
{% load staticfiles %}
<!DOCTYPE html> 
<html lang="en"> 
<head> 
	<meta charset="utf-8"> 
	{% block title %}<title>Kaizen-Twitter</title>{% endblock %}
	<link rel ="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
	<link rel ="stylesheet" href="{% static 'twit_style.css' %}">
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" ></script>
	<script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
	{% block scripts %}{% endblock %}
</head>
<body>
	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">
		<ul class="nav">
		  <li class="active">
		    <a class="brand" href="{% url 'suggestionbox:index' %}">Kaizen-Twitter</a>
		  </li>
		 <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'auth_logout' %}"> Log Out</a></li>
                    {% else %}
                    <li><a href="{% url 'auth_login' %}"><span class="glyphicon glyphicon-user"></span> Log In</a></li>
                    {% endif %}
		    <li><a href="{% url 'suggestionbox:index' %}">SuggestionBox</a></li>
		    <li><a href="{% url 'twitter:index' %}">Twitter</a></li>
		    <li><a href="http://mysite.smg247.webfactional.com">Other Apps</a></li>
                </ul>

	    </div>
	  </div>
	</div> 
	<div class="content">
	{% block content %}

	{% endblock %}
		<div class="footer">
		Created by: Stephen Goeddel<br />
		On: 10/2/2013
	</div>
	</div>

</body>

</html>

kaizen/templates/twitter_base.html
{% load staticfiles %}
<!DOCTYPE html> 
<html lang="en"> 
<head> 
	<meta charset="utf-8"> 
	{% block title %}<title>Twitter-100% improved</title>{% endblock %}
	<link rel ="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
	<link rel ="stylesheet" href="{% static 'twit_style.css' %}">
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" ></script>
	<script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
	{% block scripts %}{% endblock %}
</head>
<body>
	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">
		<ul class="nav">
		  <li class="active">
		    <a class="brand" href="{% url 'twitter:index' %}">Twitter-100% improved</a>
		  </li>
		  
		<!--
		  <li class="dropdown">
		    <a href="#"
			  class="dropdown-toggle"
			  data-toggle="dropdown">
			  Categories
			  <b class="caret"></b>
		    </a>
		    <ul class="dropdown-menu">
		     {% for category in categories %}
		     <li><a href="{% url 'suggestionbox:category' category.id %}">{{category.title}}</a></li>
		     {% endfor %}
		    </ul>
		  </li>
		-->
		 <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
		    {% if not new %}
		    	<li><a href="{% url 'twitter:profile' user.id %}">@{{user.username}}</a></li>
			<li><a href="{% url 'twitter:add_post' %}">Add Post</a></li>
		    {% endif %}
		    {% if user.is_superuser %}
			<li><a href="{% url 'admin:app_list' 'twitter' %}">Admin</a></li>
		    {% endif %}
                    <li><a href="{% url 'auth_logout' %}"> Log Out</a></li>
                    {% else %}
                    <li><a href="{% url 'auth_login' %}"><span class="glyphicon glyphicon-user"></span> Log In</a></li>
                    {% endif %}
		    <li><a href="{% url 'suggestionbox:index' %}">SuggestionBox</a></li>	
		    <li><a href="http://mysite.smg247.webfactional.com">Other Apps</a></li>
                </ul>

	    </div>
	  </div>
	</div> 
	<div class="content">
	{% block content %}

	{% endblock %}
		<div class="footer">
		Created by: Stephen Goeddel<br />
		On: 10/2/2013
	</div>
	</div>

</body>

</html>