kaizen/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kaizen.views.home', name='home'),
    # url(r'^kaizen/', include('kaizen.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^users', RedirectView.as_view(url='/')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^', include('suggestionbox.urls', namespace='suggestionbox')),
    url(r'^twitter', include('twitter.urls', namespace='twitter')),

)#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twitter/urls.py
from django.conf.urls import patterns, include, url
from twitter import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^/profile/(?P<profile_id>\d+)/$', views.profile, name='profile'),
    url(r'^/profile/follow/(?P<profile_id>\d+)/(?P<fol>\d+)/$', views.follow, name='follow'),
    url(r'^/profile/edit/(?P<profile_id>\d+)/$', views.edit_profile, name='edit_profile'),
    url(r'^/profile/add/$', views.add_profile, name='add_profile'),
    url(r'^/add_post/$', views.add_post, name='add_post'),
    url(r'^/delete_post/(?P<post_id>\d+)/$', views.delete_post, name='delete_post'),
)

twitter/models.py
from django.db import models
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User

class Profile(models.Model):
	user = models.ForeignKey(User)
	bio = models.TextField()
	image = models.ImageField(upload_to='images/%Y/%m/%d/')
	following = models.ManyToManyField('self', symmetrical=False)
	
	def __unicode__(self):
		return self.user.username

class Post(models.Model):
	profile = models.ForeignKey(Profile)
	body = models.CharField(max_length=140)
	pub_date = models.DateTimeField(auto_now_add=True)
	linked_profile = models.ForeignKey(Profile, related_name='linked_profile', null=True)

	def __unicode__(self):
		return self.body






##
##	def linked_bool(self):
##		if '@' in self.body:
##			return True
##		else:
##			return False
##
##	def linked_user(self):
##		if '@' in self.body:
##			start = self.body.find('@')
##			end = self.body.find(' ', start)
##			return self.body[start:end]
##
##	def linked(self):
##		if '@' in self.body:
##			start = self.body.find('@')
##			end = self.body.find(' ', start)
##			profile = get_object_or_404(Profile, user=self.body[start+1:end])
##			return profile.id
##		else:
##			return False
	

twitter/forms.py
from django import forms
from django.forms import ModelForm
from django import forms
from twitter.models import Profile, Post

class EditProfile(ModelForm):
	class Meta:
		model = Profile
		widgets = {
          		'bio': forms.Textarea(attrs={'rows':3, 'cols':15}),
        	}
		fields=['bio','image']

class AddPost(forms.Form):
	body = forms.CharField(max_length=140)
	linked_profile = forms.ModelMultipleChoiceField(queryset=Profile.objects.all(), required=False)
	
	def __init__(self, *args, **kwargs): #changing the lable of linked_profile, as it is not clear what that means to the user
		super(AddPost, self).__init__(*args, **kwargs)
		self.fields['linked_profile'].label = "Tag a user (optional)"


class AddProfile(ModelForm):
	class Meta:
		model = Profile
		widgets = {
          		'bio': forms.Textarea(attrs={'rows':3, 'cols':15}),
        	}
		fields=['bio','image']

	

twitter/views.py
# Create your views here.
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django import forms

from twitter.models import Profile, Post
from twitter.forms import EditProfile, AddPost, AddProfile

@login_required
def index(request):
	user = request.user
	profiles = Profile.objects.all().order_by('-id')
	
	new = True
	for profile in profiles: #I'm not certain this is the best way to do this, determining if the user has a profile
		if int(profile.id) == int(user.id):
			new = False
			break
	if not new:
		user_profile = Profile.objects.get(pk=user.id)
		context = {
		'profiles': profiles,
		'user':user,
		'new':new,
		'user_profile':user_profile,
		}
	else:
		context = {
		'profiles': profiles,
		'user':user,
		'new':new,
		}
	

	return render(request, 'twitter/index.html', context)

@login_required
def profile(request, profile_id):
	user = request.user
	profile = get_object_or_404(Profile, pk=profile_id)
	user_profile = get_object_or_404(Profile, pk=user.id)
	posts = Post.objects.all().filter(profile = profile_id).order_by('-pub_date')
	all_posts = Post.objects.filter(profile__in = profile.following.all()).order_by('-pub_date')
	mentions = Post.objects.all().filter(linked_profile = profile.id).order_by('-pub_date')
	new =False #this is in here so the navbar works
	cur_user = False

	if int(user.id) == int(profile_id): #if the current user is the same as the profile
		cur_user = True

	following = False
	for user_profile in request.user.profile_set.all():
        	if profile in user_profile.following.all():
            		following = True
            		break

	context = {
        'profile': profile,
	'user':user,
	'user_profile':user_profile,
	'posts':posts,
	'cur_user':cur_user,
	'all_posts':all_posts,
	'following':following,
	'new':new,
	'mentions':mentions,
        }

	return render(request, 'twitter/profile.html', context)

@login_required
def edit_profile(request, profile_id):
	user = request.user
	profile = get_object_or_404(Profile, pk=profile_id)
	form = EditProfile(request.POST or None, request.FILES or None, instance=profile)
	cur_user = False
	new =False #this is in here so the navbar works
	if int(user.id) == int(profile_id): #if the current user is the same as the profile
		cur_user = True

	if cur_user: #only show the form if the user owns this profile
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('twitter:profile', args=(profile.id,)))
	context = {
        'profile': profile,
	'user':user,
	'form':form,
	'new':new,
        }
	return render(request, 'twitter/edit_profile.html', context)

@login_required
def add_post(request):
	user = request.user
	profile = get_object_or_404(Profile, pk=user.id)
	
	new =False #this is in here so the navbar works

	#AddPost.base_fields['linked_profile'] = forms.ModelChoiceField(queryset=Profile.objects.filter(profile__in = profile.following.all()))
	form = AddPost(request.POST or None)
	if form.is_valid():
		cd = form.cleaned_data
		if cd.get('linked_profile'):
			linked_pro = Profile.objects.get(pk=cd.get('linked_profile'))
		else:
			linked_pro = None
		new_post = Post.objects.create(body = cd.get('body'), linked_profile = linked_pro, profile = profile )
		new_post.save()
		return HttpResponseRedirect(reverse('twitter:profile', args=(profile.id,)))
	context = {
	'user':user,
	'form':form,
	'new':new,
        }
	return render(request, 'twitter/add_post.html', context)

def add_profile(request):
	user = request.user
	profile, created = Profile.objects.get_or_create(pk=user.id,user=user)
	new =False #this is in here so the navbar works
	form = AddProfile(request.POST or None, request.FILES or None, instance=profile)

	if form.is_valid():
		profile.following.add(profile) #makes it so the new profile follows itself, which is neccessary to correctly display posts
		form.save()
		return HttpResponseRedirect(reverse('twitter:profile', args=(user.id,)))
	context = {
        'profile': profile,
	'user':user,
	'form':form,
	'new':new,
        }
	return render(request, 'twitter/add_profile.html', context)

def follow(request, profile_id, fol):
	user = request.user
	profile = get_object_or_404(Profile, pk=profile_id)
	user_profile = get_object_or_404(Profile, pk=user.id)
	if int(fol) == 1: #if we are trying to follow
		user_profile.following.add(profile)
		return HttpResponseRedirect(reverse('twitter:profile', args=(profile.id,)))
	else: #if we are trying to unfollow
		user_profile.following.remove(profile)
		return HttpResponseRedirect(reverse('twitter:index'))

def delete_post(request, post_id):
	user = request.user
	post = get_object_or_404(Post, pk=post_id)
	post.delete()
	return HttpResponseRedirect(reverse('twitter:profile', args=(user.id,)))

twitter/templates/twitter/add_post.html
{% extends 'twitter_base.html' %}
{% load staticfiles %}
{% block title %}Twitter-Add Post{% endblock %}

{% block content %}

<div class="jumbotron">
	<h1>Add a new post</h1>
	<form method="POST" action="." id="post-add-form">
	<table class="form">
                {% csrf_token %}
                {{form}}
        </table>
        <input class="btn" type="submit" value="Add Post"></input>
	</form>
</div>
{% endblock %}

twitter/templates/twitter/add_profile.html
{% extends 'twitter_base.html' %}
{% load staticfiles %}
{% block title %}Twitter-{{profile.user.username}}{% endblock %}

{% block content %}

<div class="jumbotron">
	<h1>@{{profile.user}}</h1>
	<h3>Create Your Profile</h3>
	<form method="POST" action="." id="profile-add-form" enctype="multipart/form-data">
	<table class="form">
                {% csrf_token %}
                {{form}}
        </table>
        <input class="btn" type="submit" value="Create Profile"></input>
	</form>
</div>
{% endblock %}

twitter/templates/twitter/edit_profile.html
{% extends 'twitter_base.html' %}
{% load staticfiles %}
{% block title %}Twitter-{{profile.user.username}}{% endblock %}

{% block content %}

<div class="jumbotron">
	<h1>@{{profile.user}}</h1>
	<h3>Edit Profile</h3>
	<form method="POST" action="." id="profile-edit-form" enctype="multipart/form-data">
	<table class="form">
                {% csrf_token %}
                {{form}}
        </table>
        <input class="btn" type="submit" value="Edit Profile"></input>
	</form>
</div>
{% endblock %}

twitter/templates/twitter/index.html
{% extends 'twitter_base.html' %}
{% load staticfiles %}
{% block title %}Twitter-Index{% endblock %}

{% block content %}

<div class="jumbotron">
	<h1>Welcome, @{{user.username}}.</h1>
	{% if new %}
		<h3><a href="{% url 'twitter:add_profile' %}">Create your profile now!</a></h3>
	{% else %}<!--we don't want the user doing anything until they create their profile -->
		<h3><a href="{% url 'twitter:add_post' %}">Add a new post</a>, or look at some users to follow!</h3>
	<table class="profiles">

		{% for profile in profiles %}
			<tr>
				<td><a href="{% url 'twitter:profile' profile.id %}"><img src ="{{ MEDIA_ROOT }}{{ profile.image.url }}" width=100px height=100px></a></td>
				<td><a href="{% url 'twitter:profile' profile.id %}">@{{profile.user.username}}</a></td>
				<td>{{profile.bio}}</td>
				{% if not new and not profile == user_profile %}<!--don't let them unfollow themselves-->
					{% if profile not in user_profile.following.all  %}
						<td><a href="{% url 'twitter:follow' profile.id 1 %}">Follow</a></td>
					{% else %}
						<td><a href="{% url 'twitter:follow' profile.id 0 %}">Unfollow</a></td>
					{% endif %}
				{% endif %}
			</tr>	
		{% endfor %}
	</table>
	{% endif %}
</div>
	
{% endblock %}

twitter/templates/twitter/profile.html
{% extends 'twitter_base.html' %}
{% load staticfiles %}
{% block title %}Twitter-{{profile.user.username}}{% endblock %}

{% block content %}

<div class="jumbotron">
{% if profile %}
	{% if cur_user %}
		<a href="{% url 'twitter:edit_profile' profile.id %}" class="edit">Edit Profile</a>
		<a href="{% url 'twitter:add_post' %}" class="add">Add Post</a>
	{% else %}
		{% if profile not in user_profile.following.all %}
			<a href="{% url 'twitter:follow' profile.id 1 %}" class="follow">Follow</a>
		{% else %}
			<a href="{% url 'twitter:follow' profile.id 0 %}" class="follow">Unfollow</a>
		{% endif %}
	{% endif %}
	<img src ="{{ MEDIA_ROOT }}{{ profile.image.url }}" width=150px height=150px class="profile-img">
	<h1>@{{profile.user}}'s Microblog</h1>
	<h4>A little bit about me:</h4>
	<p class="bio">{{profile.bio}}</p>
	
{% else %}
	<p>You have yet to create a profile</p>
{% endif %}	
</div>
{% if posts or all_posts %}
	
<div class="posts">
	
	{% if not cur_user %}
		<h3>What I have to say</h3>
		<table class="post-table">
			{% for post in posts %}
				
				<tr>
					<td>{% if post.linked_profile %}<a href="{% url 'twitter:profile' post.linked_profile.id %}">@{{post.linked_profile}} </a>{% endif %}{{post.body}}</td>
					<td>On: {{post.pub_date}}</td>
				</tr>
			{% endfor %}
		</table>
	{% else %}
		<h3>What people I am following have to say</h3>
		<table class="post-table">
			{% for post in all_posts %}
				
				<tr>
					<td><a href="{%url 'twitter:profile' post.profile.id %}">@{{post.profile}}:</a></td>
					<td>{% if post.linked_profile %}<a href="{% url 'twitter:profile' post.linked_profile.id %}">@{{post.linked_profile}} </a>{% endif %}{{post.body}}</td>
					<td>On: {{post.pub_date}}</td>
					{% if post.profile.id == user.id %}
						<td><a href="{% url 'twitter:delete_post' post.id %}">Delete</a></td>
					{% else %}
						<td><a href="{% url 'twitter:follow' post.profile.id 0 %}">Unfollow</a></td>
					{% endif %}
				</tr>
			{% endfor %}
		</table>
	{% endif %}
</div>
{% endif %}
{% if mentions %}
<div class ="mentions">
	<h3>What others have to say about me</h3>
	<table class="post-table">

		{% for mention in mentions %}
			
			<tr>
				<td><a href="{% url 'twitter:profile' mention.profile.id %}">@{{mention.profile}}:</a></td>
				<td>@{{mention.linked_profile}} {{mention.body}}</td>
				<td>On: {{mention.pub_date}}</td>
			</tr>
		{% endfor %}
	</table>


</div>
{% endif %}
{% endblock %}